project:
  type: website
  output-dir: docs

website:
  title: "Philanthropic Giving to EJ-Communities (Prototype 1)"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - corporate.qmd
      - nonprofit.qmd
      - comp_analysis.qmd
    right:
      - icon: twitter
        href: http://linktr.ee/theundivide
      - icon: github
        href: https://github.com/TheUndivideProject
        aria-label: GitHub

  page-footer:
    right: |
      Made with [Quarto](https://quarto.org/)<br>

    
format:
  html:
    css: styles.css
    toc: true



