project:
  type: website
  output-dir: docs

website:
  title: "Philanthropic Giving to EJ-Communities (Prototype 1)"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - corporate.qmd
      - nonprofit.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



